### ISSUE TITLE
Assertion Error on rule bcalm_catlas_input

### ISSUE THREAD

**Issue by taylorreiter** [spacegraphcats/spacegraphcats#225]
I received an assertion error for rule `bcalm_catlas_input`. It started running fine, but then there were a series of `-> but not -> ...` statements printed to the screen. It then failed with an assertion error. 

I tried running this on two machines (macOS and ubuntu) and received the same error on both.

Any ideas as to what may be happening/how to fix it? The reads I'm running this on are about ~500MB and the queries are small. 

```
rule bcalm_catlas_input:
    input: CSM67UFZ_r1_k51/bcalm.CSM67UFZ_r1_k51.k51.unitigs.fa
    output: CSM67UFZ_r1_k51_k51_r1/cdbg.gxt, CSM67UFZ_r1_k51_k51_r1/contigs.fa.gz, CSM67UFZ_r1_k51_k51_r1/contigs.fa.gz.info.csv
    jobid: 3

taylor/miniconda3/envs/space/bin/python -m spacegraphcats.cdbg.bcalm_to_gxt  -k 51 CSM67UFZ_r1_k51/bcalm.CSM67UFZ_r1_k51.k51.unitigs.fa CSM67UFZ_r1_k51_k51_r1/cdbg.gxt CSM67UFZ_r1_k51_k51_r1/contigs.fa.gz
... 620000

194 -> 197, but not 197 -> 194
198 -> 683352, but not 683352 -> 198
198 -> 194, but not 194 -> 198
197 -> 1297934, but not 1297934 -> 197
208 -> 211, but not 211 -> 208
209 -> 1206208, but not 1206208 -> 209
209 -> 1297934, but not 1297934 -> 209
```
```
Traceback (most recent call last):
  File "taylor/miniconda3/envs/space/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "taylor/miniconda3/envs/space/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "taylor/miniconda3/envs/space/lib/python3.6/site-packages/spacegraphcats/cdbg/bcalm_to_gxt.py", li$
e 375, in <module>
    main(sys.argv[1:])
  File "taylor/miniconda3/envs/space/lib/python3.6/site-packages/spacegraphcats/cdbg/bcalm_to_gxt.py", li$e 257, in main
    neighbors, sequences, mean_abunds, sizes = read_bcalm(unitigs, debug, k)
  File "taylor/miniconda3/envs/space/lib/python3.6/site-packages/spacegraphcats/cdbg/bcalm_to_gxt.py", li$e 214, in read_bcalm
    assert not fail
AssertionError
[Tue Jun 25 15:46:11 2019]
```

**Comment by taylorreiter** [comment]
I successfully tried the test data from dory-test:
```
git clone https://github.com/spacegraphcats/spacegraphcats-dory-example.git
cd spacegraphcats-dory-example/
python3 -m spacegraphcats config.yaml extract_reads
```

Given that this worked, I edited my config file to look like the one in dory-test (except I chose to use a k-size of 51), but still received the same assertion error. I therefore infer that there is something wrong with my sequencing files. 

My reads/fasta (data) look like this:
```
>CAPPMANXX170326:7:1101:10000:10168
TTCCGGTACCGGACAGACCGAAGAAGATAGCGGTATTCTCACCGTTTAAGTCAGTATTAGCGGAGCAGTGCATGGAAGCGATGCCCTTTAACGGCAGGTAG
>CAPPMANXX170326:7:1101:10007:24280
GGACAAGGATATGTCATTCAAATGACATTCCGTCTAGGTGAGGATGTTGTTGGTTTCCGCCGTAATTATAATGGGGTATGGGGAGATTTTAGGTCTTTTGT
>CAPPMANXX170326:7:1101:10019:50492
GAACTGTATGTTGAATGGACCGGAAATGTTCAACTCTTTTGCAATGCGACGGCTTATCTTCTTAATCTGTCTTGCTGTTGCAAAATAGATATGCTGAGCAG
>CAPPMANXX170326:7:1101:10021:36149
CATTAAGAGTACGCCAGCTATTGTCATCAAATGATAGCTTTTCTGCTCCAACTATATCTCCTAGATAAAATTTCCAATTTTTATCAAAGTTTGTTGTTAC
>CAPPMANXX170326:7:1101:10029:94090
ACATAATACTTAAAAAACAAAAGAAAATCTTATCTTTTTTCACTTTTTGCTATGTAAATTGAGAGAGAAGCCGGAACTCAGCTTTTATATTTTCTAACTAT
```

My query looks like this (I've only included two sequences, there are a few more):
```
>VIRSorter_k99_15129_flag=1_multi=16_0000_len=2380-cat_1
AAACTGAATGATTTAAATAAGATTTTTATTAATGAAAATAAATAGTATTAACCTTTAATTTTGTTGTTATGGCAAATATTATGTCGCTAAAAAGTCTTAGGAACAAGACTTCCCGAAATGGTTTCGACCTTTCGTTTAAGAAAAATTTTACTGCTAAAGCTGGTGAACTTCTTCCCGTTATGGTG
AAAGAGGTACTCCCTGGTGATAGCTTTAAAATTGACCTTAAATCTTTTACTCGTACACAACCTATTAATACGGCTGCATTCGCTCGTATTCGTGAGTATTACGATTTCTATTTTGTTCCTTACGATTTACTATGGAATAAGGCAAATACAGTGTTGACGCAAATGTATGATAACCCACAACATTC
TGTGTCTATGAATCCTACAGATAATTTTGTTTTGTCCGGTACTATGCCCTCTATTACTGCCTCCGGTCTTGCAAAGTATCTTGTTAGTGTTAATGACAGTGGCGAGGAACTAAATTATTTTGGTTATAATCGTGCGCTTTGCTCGGCTAAGTTAATGGAATATCTTGGTTATGGTAATTTTTATC
GTTATGCTAAAGGCGACCAATTTACTTGGGATGAACATCCGTTATTAAATAATCTAAATTTTAATATTTTTGGTTTCCTTGCCTATCAAAAGATTTATTCAGATTATTATCGTGATAGTCAATGGGAACGTATTGCTCCGTCTACCTTTAATGTTGATTTTATGGACGGTTCTGGTAATAATAGC
ATAGAACCTTATCTTAATGGTGATTCCTCATCTGATATTATAACTCATTATAATTTGTTTGATTTACGCTATTGTAATTGGCAAAAGGATTTATTTCACGGTTTAGTTCCTCATCAACAATATGGTACTGCTTCTGCGGTTGATGTTTTCTTGCCAAGAAGTCTTTCTTTTGGGGATTTGCATCA
AAAACCATCTTCCGCTTTTCAGGTTGGTCAAAACTTATTAAGTTCTTCGGTATATTTGAATAATCCTTCTTCTGAAAGTGTCTTATCTTTTTCAATTCTTGCACTTCGTCAAGCTGAATTCTTGCAGAAATGGAAAGAAATTACGCAATCAGGTAATAAAGATTATAAAGACCAAATAGAGAAAC
ACTGGGGTGTTTCTGCTGGTGATGCTCTTTCTGAGATGTGTTCCTATCTTGGTGGTATTGCTTCAAGCCTTGATATTAATGAGGTTGTAAATAGTAATATTACAGGTGATAATGCTGCCGATATAGCTGGCAAAGGAACTGGTGTATCTAATGGTTATATAAATTTTGATGCTGGTGCTAAATAT
GGTGTTATTATGTGTATTTATCATTGTCTGCCTATGTTGGACTATACGGCTGATTTGGTTGAAAGCGCATTTATAAAGGTAAATGCTGCTGATTATGCTATTCCTGAATTTGATCGTGTCGGTATGGAAGCTGTTCCTTTTGCTAAAATGATTAACCCATTAAAAAATGAGGATGGTCTTAATTT
TACGCCGTTTGCTTCTATGGTAATGGGCTATGCACCTCGTTATATTGATTATAAAACTTCAGTAGATTCTTCTGTCGGTGGTTTTAGAGATACTTTAAAAAATTGGGTTATTTCTTATGGTAATACTTCGATTTGTAATCAATTATCTACTTTGAAAGGTCCTGCTCTTCCTGGTCCTGAACCTT
CCGTTTCTTATATAAATTATTCATTCTTTAAGGTTAATCCAAATTGTTTAGATCCTTTGTTTGCGGTTGCTGTTGACAGTGAAATATCTACAGACCAATTTTTGTGTAGTTCTTTCTTTGATGTTAAGGTCGTCCGAAATCTTGACACGGATGGTTTACCTTATTAGTGTATAAAGTCGTTTATA
TTTACTAATTTATAAATATATTTTATTATGTGGTGTACTAAGAGACGTGTAGAACCTTTTCAAGAAGAATTTAAGCCTTATAATATATCTTCTAAGGACTTAAGACTAAGTGAATTTCTTGAAAATAGTCCTGTTAATGAATTTTGTTATGAAAGATTGGAAGTAAATGGAAATGAGGTTGTTAC
TCTTACATCTGACATTTATATGCTATTCAATCAGCAACGTCTAGACCGTATGAGCCGTGAGCGCTTGGTTGCTTACTTTGATAATGTTTCTGTGAGTGAGCCTAAAATGCGTGAATTACGCTCTAAGTTGAGCGACGACCAATTATGCAGTTTTGTGAAGTCGCGGTTTATACAATCACCGTCTG
AATTGATGGCATGGTCGGAATATCTGATGAGTTCGCAGGATGAGATGATAGCGGCCGCCGCTGCCGAACAACAGACCGAACAATCTACTAAGCATGAGGTAGACCCGACTCAAGAGCCCTAAAATATATTTTTTTCCTTTTCTTTCGAGACGTGCAAAAA
>VIRSorter_k99_5534_flag=1_multi=17_0000_len=2372-cat_1
GATTCTAAGAGCTTCAATGCTGAGGCGTTCAAGTACATGGTGGACCGTGTTCCTAACCTCAACCTGAACGAGCTCAAGAAGTCTCGTGCCCTTGCGGGCAACCCCGACATCCGCGGCGTGTTTACCGCCCAGAACGGTACCGCGTATGCTCGTCTGGCTATGCGCGGCCTGATTGACGGCGACGC
CGTTAACTACGACGGCCAGACCGACATCACCGCAACCTCCACTAAGACCTTCGAGCAGGGCGTCGTTGTCATCGGCCGTGCGAAGGCTTGGACTGAGAGGGACTTTTCCTATGACATTACTGGCGGCGTTGACTTCATGGGCAACATCAGCCAGCAGGTGGCCGAGTACAAGGACCATCTGGACC
AGAACACGATTCTCGCTATTCTCGCCGGCATTTTCGCTATGACCGACACGAAGAGCAAGGAGTTCGTCACTAAGCACACTCTCGACGTGACCGGCGTCGGTACTGGCGTTATGGCGGCTTCTACTTTGAACTCCGCAGCGAACAAGGCTTGCGGCGCGAACAAGAAGAAGTTCAAGCTCGTGTTC
ATGCACTCTGACGTTTCTACCGGTCTTGAGAATCTCAACCTGATTGAGCGTCTCAAGTATACCGATAAGGACGGCATTACCCGCGACCTCGAGCTCGGCACGTGGAACGGTAAGCTCGTTGTCGTTGATGACGACATGCCGGCTTCTGATGGCTACTTCGACGCCGACGCCAACACTGACGGCGC
ATTGAAGATTGTCGCTTCCGGTACTCCTGCCGCAGGTGAGATTCTTCTGTCTAAGGTAACTCCGTACTTCGGCAGCAAGACTCTGGCTGCGAACGACTACGTTGTTGCCGGCACTCAGTATACGACCTATGTTCTCGGCGAAGGCGCTATCTCCTACGAGGACATCGGCGCGAAGGTGCCTTATG
AGATGAGCCGCGACCCGAAGACCAACGGCGGTGAGGACACTCTGTACACTCGTCAGCGCAAGGTCTTCGCTCCTTACGGTATCTCTTATGAGAAGGCTTCTCAGACTTCTCTGTCTCCTACCGATACCGAGCTCAAGAACGGCGCGAACTGGGCATTGGTGCATTCCGGTGAGACTACCGCGTCT
CAGCGTTCCTACATCAACCACAAGGCCATTCCTATCGCGCGTATCTTCTCCAGAGGTTAAGGCCTATGGAGATACTCGCGGCAGTAACCGCCCGACTGTCGGCCCTCGGTTATACCGTGACCGAGACCGACAGCGCGGCGCTTGATTACAATATTAAGAAAGCCGAGACGACCCTAAAGGTACGA
ACGAATCAGCTCGAAGTGCCCGAGGGTCTTTTCTATGTCTGGGCGGATATGGCTGCGGGCATGTTCCTCACAGACAAGAAGGCTTCCGGCGCGCTCTCCGAGGTCTACGACTTCGACGCGCCGGCTAAGAGCATTTCTGAAGGCGACACCTCCGTCACCTTCGCGATTGCAGATACCGGCTCTTT
CGAGGACCAGTTCGACGCAATGCTCGCGAAGATGGTAAACCCCGACGCGGAGCTTATCGCAGCGTTCAGGAGGTTGGTATGGTGAAAAGCTATCAGGACGCTCTACGGAGGCTCTGGGACGGCCTCTGTGACGTTTATGTCCTCGAGACAGCGGTAAATAAGGCAAACGGCCGGGATGAGCCCAC
GGAGGTCCAGAAGCTCCACGGCGAGCCCTGCCGTTTGTCCTTCTCAAGTATCTCAAGCACGACCGAGCAGGACAGCGCGCCGCTGATTCAGCAGTCTGTCAAGCTCTTCGTCTCGAAGACCGTAGAAATCCCGGCGGGCTCTAAGATAGTCGTAACGCAGGAAGGCCGGACTACCGCCTACGCGA
GGTCCGGCGAGCCTGCGGTCTATAGCTGTCATCAGGAGATACCGCTCGTCCCGTTCAAGGAGTACGCCTAATGTCCCGCTGGGGACGCTGCGACTTCTCTCAGTTCAGGGAGTTTGCGAAAGGCTTTGAAAAGCTGAGCGACTCTGAGATAGACGACCTCTGCGTGGCTTGCAGCAAAGAGCTCG
CCGCAAGGCTTCTGGCTCTCGTTATTCCGGCTACCCCGGTCGGCAAGTACCCGAAAGGCTCCGGCAAGAAAGGCGGTACCCTCCGCCGAGGCTGGGGCGCTAAGAACGGCAAAGCGGGGCGCGAGTACGCGCAGTCCCTGACCGTCACAAAGTCCGGGAATACATATATGGTCGAAATCATAAAT
CCGGTCGAGTACGCCTCGTATGTCGAGTTCGGTCACCGTACCGTAAGCGGCGGCTGGGTCGAGGGCCGGTACATGCTGACTATCTCCGAGGAAAAGCTGAAACGAATCGCCCCGTCTGTGCTTGAGAAGATGGTGCTCCGAAAGCTGAAGGA
```
and my config file looks like this:
```
catlas_base: CSM67UFZ_r1_k51
input_sequences:
- CSM67UFZ.fastq.gz.donut.fa
keep_graph_pendants: true
ksize: 51
radius: 1
search:
- CSM67UFZ_VIRSorter_cat-1.fasta
searchquick:
- CSM67UFZ_VIRSorter_cat-1.fasta
```
@ctb can you see any obvious problems?

**Comment by taylorreiter** [comment]
Installing `bcalm` from github resolves this issue:

```
git clone --recursive https://github.com/GATB/bcalm
cd bcalm
mkdir build;  cd build;  cmake ..;  make -j 8
cd ..
export PATH=$PATH:~/taylor/bcalm/build/bcalm
```

**Comment by ctb** [comment]
This was caused by a recurrent problem in bcalm's compilation, see https://github.com/GATB/bcalm/issues/44#issuecomment-509963038 for discussion and fix!
