### ISSUE TITLE
In rule build_catlas: IndexError: list index out of range

### ISSUE THREAD

**Issue by taylorreiter** [spacegraphcats/spacegraphcats#259]
I'm attaching the slurm log file from that produced this error. I can't figure out what causes this error, however when I look at the fastq files, there are only 880 reads in each of the forward and reverse files. I think this is failing because too many things are removed. Could there be a more helpful error message for this?
[slurm-17514094.txt](https://github.com/spacegraphcats/spacegraphcats/files/4104195/slurm-17514094.txt)

**Comment by ctb** [comment]
I think this is @microgravitas territory :). Can you post or otherwise provide the input files, if they're that small?

**Comment by ctb** [comment]
The relevant error:
```
% /home/tereiter/github/ibd/.snakemake/conda/da81c201/bin/python -m spacegraphcats.catlas.catlas --no_checkpoint PSM7J1BH_k31_r1 1
...
Catlas level 1 complete
Traceback (most recent call last):
  File "/home/tereiter/github/ibd/.snakemake/conda/da81c201/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/tereiter/github/ibd/.snakemake/conda/da81c201/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tereiter/github/ibd/.snakemake/conda/da81c201/lib/python3.7/site-packages/spacegraphcats/catlas/catlas.py", line 359, in <module>
    main(args)
  File "/home/tereiter/github/ibd/.snakemake/conda/da81c201/lib/python3.7/site-packages/spacegraphcats/catlas/catlas.py", line 340, in main
    cat = CAtlas.build(proj)
  File "/home/tereiter/github/ibd/.snakemake/conda/da81c201/lib/python3.7/site-packages/spacegraphcats/catlas/catlas.py", line 219, in build
    proj.root.vertex = list(nodes.keys())[0]
IndexError: list index out of range
```

**Comment by taylorreiter** [comment]
Yes! They can be downloaded here: https://ibdmdb.org/tunnel/static/HMP2/WGS/1818/PSM7J1BH.tar

so 
```
wget https://ibdmdb.org/tunnel/static/HMP2/WGS/1818/PSM7J1BH.tar
tar xf PSM7J1BH.tar
```

Will output two small fastq files.

**Comment by ctb** [comment]
I reproduce the error with the following conf file.
```
catlas_base: PSM7J1BH
input_sequences:
- PSM7J1BH/PSM7J1BH_R1.fastq.gz
- PSM7J1BH/PSM7J1BH_R2.fastq.gz
ksize: 31
radius: 1
search:
- foo
searchquick:
- bar
shadow_ratio_maxsize: 1000

hashval_ksize: 51
hashval_queries: data/twofoo-k51-hashval-queries.txt
```

**Comment by ctb** [comment]
See https://github.com/spacegraphcats/spacegraphcats/pull/265. Run it with:

```
python -m spacegraphcats PSM7J1BH-conf.yaml
```
