### ISSUE TITLE
bcalm_catlas_input error, possibly installation issue

### ISSUE THREAD

**Issue by jessicamizzi** [spacegraphcats/spacegraphcats#276]
Hello! I'm having some trouble getting the twofoo example from the [running spacegraphcats page](https://github.com/spacegraphcats/spacegraphcats/blob/master/doc/running-spacegraphcats.md) page to work. (And I'm assuming that if the twofoo example doesn't work, then I haven't succeeded with installing spacegraphcats and running my own data through it isn't useful to do.)

Here are commands I've run so far:

``` 
git clone https://github.com/spacegraphcats/spacegraphcats/
```
```
conda env create -f spacegraphcats/environment.yml -n sgc
```
```
conda activate sgc
```
```
cd spacegraphcats
python -m spacegraphcats dory-test search
```
And this is successful! Moving on to twofoo:
```
make twofoo.fq.gz
```
Now this command gives me an error:
```
python -m spacegraphcats twofoo search
```
Here is my output:
```
Found configfile at /Users/jessicamizzi/spacegraphcats/spacegraphcats/./conf/twofoo.yaml
--------
details!
	snakefile: /Users/jessicamizzi/spacegraphcats/spacegraphcats/./conf/Snakefile
	config: /Users/jessicamizzi/spacegraphcats/spacegraphcats/./conf/twofoo.yaml
	targets: ['search']
--------
...updating input file twofoo.fq.gz with prefix /Users/jessicamizzi/spacegraphcats
...updating input file data/2.fa.gz with prefix /Users/jessicamizzi/spacegraphcats
...updating input file data/47.fa.gz with prefix /Users/jessicamizzi/spacegraphcats
...updating input file data/63.fa.gz with prefix /Users/jessicamizzi/spacegraphcats
...updating input file data/twofoo-k51-hashval-queries.txt with prefix /Users/jessicamizzi/spacegraphcats
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	bcalm_catlas_input
	1	build_catlas
	1	make_contigs_kmer_index
	1	search
	4

[Mon Jun 22 16:55:00 2020]
rule bcalm_catlas_input:
    input: twofoo/bcalm.twofoo.k31.unitigs.fa
    output: twofoo_k31_r1/cdbg.gxt, twofoo_k31_r1/contigs.fa.gz, twofoo_k31_r1/contigs.fa.gz.info.csv
    jobid: 3

/Users/jessicamizzi/software/miniconda3/envs/sgc/bin/python -m spacegraphcats.cdbg.bcalm_to_gxt  -k 31 twofoo/bcalm.twofoo.k31.unitigs.fa twofoo_k31_r1/cdbg.gxt twofoo_k31_r1/contigs.fa.gz
reading unitigs from twofoo/bcalm.twofoo.k31.unitigs.fa
...read 206855 unitigs
59 -> 126440, but not 126440 -> 59
60 -> 127585, but not 127585 -> 60
60 -> 32391, but not 32391 -> 60
58 -> 71865, but not 71865 -> 58
58 -> 88314, but not 88314 -> 58
58 -> 150982, but not 150982 -> 58
```
There are a bunch of lines like above, so I'm skipping the majority of them.
```
206644 -> 18707, but not 18707 -> 206644
206664 -> 1278, but not 1278 -> 206664
206685 -> 26536, but not 26536 -> 206685
206800 -> 27976, but not 27976 -> 206800
206800 -> 10573, but not 10573 -> 206800
Traceback (most recent call last):
  File "/Users/jessicamizzi/software/miniconda3/envs/sgc/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/jessicamizzi/software/miniconda3/envs/sgc/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jessicamizzi/spacegraphcats/spacegraphcats/cdbg/bcalm_to_gxt.py", line 377, in <module>
    main(sys.argv[1:])
  File "/Users/jessicamizzi/spacegraphcats/spacegraphcats/cdbg/bcalm_to_gxt.py", line 259, in main
    neighbors, sequences, mean_abunds, sizes = read_bcalm(unitigs, debug, k)
  File "/Users/jessicamizzi/spacegraphcats/spacegraphcats/cdbg/bcalm_to_gxt.py", line 215, in read_bcalm
    assert not fail
AssertionError
[Mon Jun 22 16:55:12 2020]
Error in rule bcalm_catlas_input:
    jobid: 3
    output: twofoo_k31_r1/cdbg.gxt, twofoo_k31_r1/contigs.fa.gz, twofoo_k31_r1/contigs.fa.gz.info.csv
    shell:
        /Users/jessicamizzi/software/miniconda3/envs/sgc/bin/python -m spacegraphcats.cdbg.bcalm_to_gxt  -k 31 twofoo/bcalm.twofoo.k31.unitigs.fa twofoo_k31_r1/cdbg.gxt twofoo_k31_r1/contigs.fa.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job bcalm_catlas_input since they might be corrupted:
twofoo_k31_r1/cdbg.gxt, twofoo_k31_r1/contigs.fa.gz, twofoo_k31_r1/contigs.fa.gz.info.csv
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/jessicamizzi/spacegraphcats/.snakemake/log/2020-06-22T165500.022379.snakemake.log
```
My snakemake log file is here:
```
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       bcalm_catlas_input
        1       build_catlas
        1       make_contigs_kmer_index
        1       search
        4

[Mon Jun 22 16:55:00 2020]
rule bcalm_catlas_input:
    input: twofoo/bcalm.twofoo.k31.unitigs.fa
    output: twofoo_k31_r1/cdbg.gxt, twofoo_k31_r1/contigs.fa.gz, twofoo_k31_r1/contigs.fa.gz.info.csv
    jobid: 3

/Users/jessicamizzi/software/miniconda3/envs/sgc/bin/python -m spacegraphcats.cdbg.bcalm_to_gxt  -k 31 twofoo/bcalm.twofoo.k31.unitigs.fa twofoo_k31_r1/cdbg.gxt twofoo_k31_r1/contigs.fa.gz
[Mon Jun 22 16:55:12 2020]
Error in rule bcalm_catlas_input:
    jobid: 3
    output: twofoo_k31_r1/cdbg.gxt, twofoo_k31_r1/contigs.fa.gz, twofoo_k31_r1/contigs.fa.gz.info.csv
    shell:
        /Users/jessicamizzi/software/miniconda3/envs/sgc/bin/python -m spacegraphcats.cdbg.bcalm_to_gxt  -k 31 twofoo/bcalm.twofoo.k31.unitigs.fa twofoo_k31_r1/cdbg.gxt twofoo_k31_r1/contigs.fa.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job bcalm_catlas_input since they might be corrupted:
twofoo_k31_r1/cdbg.gxt, twofoo_k31_r1/contigs.fa.gz, twofoo_k31_r1/contigs.fa.gz.info.csv
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/jessicamizzi/spacegraphcats/.snakemake/log/2020-06-22T165500.022379.snakemake.log
```

When I run bcalm at the command line, I get a print out of help options for it so it seems to be running properly. I got this same error when following the installation instructions here: [https://github.com/spacegraphcats/spacegraphcats-twofoo-example](https://github.com/spacegraphcats/spacegraphcats-twofoo-example). I poked around some closed issues to find some ideas and tried updating my snakemake and installing bcalm from the github repo as suggested by Taylor in #225, but this also didn't solve the issue. I seem to have the same output as #220 where running `bcalm -in data/dory-subset.fa -out dory-bcalm.unitigs.fa -kmer-size 31 -abundance-min 1` doesn't give me `dory-bcalm.unitigs.fa` but instead gives me `dory-bcalm.unitigs.fa.h5` and some intermediate files.

Thanks in advance for the help! Please let me know if there's any other information I can provide!

**Comment by ctb** [comment]
hi @jessicamizzi thank you for the great error report!

yes, I think you ran into the bcalm error in #225.

please try with the latest install instructions for twofoo (or in this repo)! it worked for me on farm just now.

**Comment by taylorreiter** [comment]
Hi @jessicamizzi 

If what @ctb suggested does not work, can you erase all output directories and try running two foo with more ram? There's one step in spacegraphcats that fails when there isn't enough ram, but snakemake doesn't recognize that it has failed and tries to keep running. Subsequent steps encounter the half-finished file and throw and AssertionError.

I'm not sure that's what is happening here, but worth a try if install instructions don't solve it

**Comment by jessicamizzi** [comment]
Thanks for the help! Unfortunately, it looks like I'm getting the same error even after following @ctb's instructions. I deleted the spacegraphcats repo and sgc conda environment on my laptop, then here's what I ran:

```
git clone https://github.com/spacegraphcats/spacegraphcats/
conda env create -f spacegraphcats/environment.yml -n sgc
conda activate sgc
```

Then, from [twofoo-example](https://github.com/spacegraphcats/spacegraphcats-twofoo-example/blob/master/README.md):

```
git clone https://github.com/spacegraphcats/spacegraphcats-twofoo-example
cd spacegraphcats-twofoo-example/
snakemake
```

Things seems to start out fine, but then the same error gets thrown:
```
/Users/jessicamizzi/software/miniconda3/envs/sgc/lib/python3.7/site-packages/spacegraphcats/snakemake.py:31: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  jj = yaml.load(fp)
/Users/jessicamizzi/software/miniconda3/envs/sgc/lib/python3.7/site-packages/spacegraphcats/snakemake.py:60: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  jj = yaml.load(fp)
/Users/jessicamizzi/software/miniconda3/envs/sgc/lib/python3.7/site-packages/spacegraphcats/snakemake.py:7: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  jj = yaml.load(fp)
/Users/jessicamizzi/software/miniconda3/envs/sgc/lib/python3.7/site-packages/spacegraphcats/snakemake.py:85: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  jj = yaml.load(fp)
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	build
	1	download_akker
	1	download_shew
	1	extract
	1	make_twofoo
	1	search
	7

[Tue Jun 23 10:11:14 2020]
rule download_akker:
    output: data/akker-reads.abundtrim.gz
    jobid: 6

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   459  100   459    0     0    830      0 --:--:-- --:--:-- --:--:--   828
100 27.9M  100 27.9M    0     0  5164k      0  0:00:05  0:00:05 --:--:-- 7488k
[Tue Jun 23 10:11:21 2020]
Finished job 6.
1 of 7 steps (14%) done

[Tue Jun 23 10:11:21 2020]
rule download_shew:
    output: data/shew-reads.abundtrim.gz
    jobid: 5

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   459  100   459    0     0    898      0 --:--:-- --:--:-- --:--:--   898
100 26.0M  100 26.0M    0     0  4997k      0  0:00:05  0:00:05 --:--:-- 7370k
[Tue Jun 23 10:11:26 2020]
Finished job 5.
2 of 7 steps (29%) done

[Tue Jun 23 10:11:26 2020]
rule make_twofoo:
    input: data/shew-reads.abundtrim.gz, data/akker-reads.abundtrim.gz
    output: data/twofoo.fq.gz
    jobid: 4

[Tue Jun 23 10:14:45 2020]
Finished job 4.
3 of 7 steps (43%) done

[Tue Jun 23 10:14:45 2020]
rule build:
    input: data/twofoo.fq.gz
    output: twofoo/bcalm.twofoo.k31.unitigs.fa, twofoo_k31_r1/catlas.csv, twofoo_k31_r1/cdbg.gxt, twofoo_k31_r1/contigs.fa.gz, twofoo_k31_r1/contigs.fa.gz.indices, twofoo_k31_r1/contigs.fa.gz.info.csv, twofoo_k31_r1/contigs.fa.gz.mphf, twofoo_k31_r1/first_doms.txt
    jobid: 3

--------
details!
	snakefile: /Users/jessicamizzi/software/miniconda3/envs/sgc/lib/python3.7/site-packages/spacegraphcats/./conf/Snakefile
	config: config.yaml
	targets: ['build']
--------
...updating input file data/twofoo.fq.gz with prefix /Users/jessicamizzi/spacegraphcats-twofoo-example
...updating input file query/2.fa.gz with prefix /Users/jessicamizzi/spacegraphcats-twofoo-example
...updating input file query/47.fa.gz with prefix /Users/jessicamizzi/spacegraphcats-twofoo-example
...updating input file query/63.fa.gz with prefix /Users/jessicamizzi/spacegraphcats-twofoo-example
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	bcalm_catlas_input
	1	bcalm_cdbg
	1	bcalm_cdbg_inpfiles
	1	build
	1	build_catlas
	1	make_contigs_kmer_index
	6

[Tue Jun 23 10:14:46 2020]
rule bcalm_cdbg_inpfiles:
    input: /Users/jessicamizzi/spacegraphcats-twofoo-example/data/twofoo.fq.gz
    output: twofoo/bcalm.twofoo.k31.inputlist.txt
    jobid: 5
    wildcards: catlas_base=twofoo, ksize=31

...updating input file data/twofoo.fq.gz with prefix /Users/jessicamizzi/spacegraphcats-twofoo-example
...updating input file query/2.fa.gz with prefix /Users/jessicamizzi/spacegraphcats-twofoo-example
...updating input file query/47.fa.gz with prefix /Users/jessicamizzi/spacegraphcats-twofoo-example
...updating input file query/63.fa.gz with prefix /Users/jessicamizzi/spacegraphcats-twofoo-example
Job counts:
	count	jobs
	1	bcalm_cdbg_inpfiles
	1
[Tue Jun 23 10:14:46 2020]
Finished job 5.
1 of 6 steps (17%) done

[Tue Jun 23 10:14:46 2020]
rule bcalm_cdbg:
    input: twofoo/bcalm.twofoo.k31.inputlist.txt
    output: twofoo/bcalm.twofoo.k31.unitigs.fa
    jobid: 4
    wildcards: catlas_base=twofoo, ksize=31

(bcalm >& /dev/null || (printf '**\n**\n** Cannot run BCALM 2! Please install it and make sure it is on your path!\n**\n**\n'; exit 1)) && (bcalm >& /dev/null && bcalm -in twofoo/bcalm.twofoo.k31.inputlist.txt -out twofoo/bcalm.twofoo.k31 -kmer-size 31 -abundance-min 1 >& twofoo/bcalm.twofoo.k31.unitigs.fa.log.txt && rm -f twofoo/bcalm.twofoo.k31.{h5,unitigs.fa.glue*} || printf '\n**\n** ERROR running BCALM 2; err output in dory/bcalm.dory.k21.unitigs.fa.log.txt\n**\n')
[Tue Jun 23 10:16:03 2020]
Finished job 4.
2 of 6 steps (33%) done

[Tue Jun 23 10:16:03 2020]
rule bcalm_catlas_input:
    input: twofoo/bcalm.twofoo.k31.unitigs.fa
    output: twofoo_k31_r1/cdbg.gxt, twofoo_k31_r1/contigs.fa.gz, twofoo_k31_r1/contigs.fa.gz.info.csv
    jobid: 3

/Users/jessicamizzi/software/miniconda3/envs/sgc/bin/python3.7 -m spacegraphcats.cdbg.bcalm_to_gxt  -k 31 twofoo/bcalm.twofoo.k31.unitigs.fa twofoo_k31_r1/cdbg.gxt twofoo_k31_r1/contigs.fa.gz
reading unitigs from twofoo/bcalm.twofoo.k31.unitigs.fa
...read 206855 unitigs
14 -> 85857, but not 85857 -> 14
13 -> 172070, but not 172070 -> 13
13 -> 116207, but not 116207 -> 13
90 -> 50053, but not 50053 -> 90
# more numbers here
206559 -> 12690, but not 12690 -> 206559
206729 -> 14552, but not 14552 -> 206729
206748 -> 4969, but not 4969 -> 206748
206774 -> 26027, but not 26027 -> 206774
Traceback (most recent call last):
  File "/Users/jessicamizzi/software/miniconda3/envs/sgc/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/jessicamizzi/software/miniconda3/envs/sgc/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jessicamizzi/software/miniconda3/envs/sgc/lib/python3.7/site-packages/spacegraphcats/cdbg/bcalm_to_gxt.py", line 377, in <module>
    main(sys.argv[1:])
  File "/Users/jessicamizzi/software/miniconda3/envs/sgc/lib/python3.7/site-packages/spacegraphcats/cdbg/bcalm_to_gxt.py", line 259, in main
    neighbors, sequences, mean_abunds, sizes = read_bcalm(unitigs, debug, k)
  File "/Users/jessicamizzi/software/miniconda3/envs/sgc/lib/python3.7/site-packages/spacegraphcats/cdbg/bcalm_to_gxt.py", line 215, in read_bcalm
    assert not fail
AssertionError
[Tue Jun 23 10:16:20 2020]
Error in rule bcalm_catlas_input:
    jobid: 3
    output: twofoo_k31_r1/cdbg.gxt, twofoo_k31_r1/contigs.fa.gz, twofoo_k31_r1/contigs.fa.gz.info.csv
    shell:
        /Users/jessicamizzi/software/miniconda3/envs/sgc/bin/python3.7 -m spacegraphcats.cdbg.bcalm_to_gxt  -k 31 twofoo/bcalm.twofoo.k31.unitigs.fa twofoo_k31_r1/cdbg.gxt twofoo_k31_r1/contigs.fa.gz
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job bcalm_catlas_input since they might be corrupted:
twofoo_k31_r1/cdbg.gxt, twofoo_k31_r1/contigs.fa.gz, twofoo_k31_r1/contigs.fa.gz.info.csv
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/jessicamizzi/spacegraphcats-twofoo-example/.snakemake/log/2020-06-23T101445.871583.snakemake.log
[Tue Jun 23 10:16:20 2020]
Error in rule build:
    jobid: 3
    output: twofoo/bcalm.twofoo.k31.unitigs.fa, twofoo_k31_r1/catlas.csv, twofoo_k31_r1/cdbg.gxt, twofoo_k31_r1/contigs.fa.gz, twofoo_k31_r1/contigs.fa.gz.indices, twofoo_k31_r1/contigs.fa.gz.info.csv, twofoo_k31_r1/contigs.fa.gz.mphf, twofoo_k31_r1/first_doms.txt
    shell:
        /Users/jessicamizzi/software/miniconda3/envs/sgc/bin/python3.7 -m spacegraphcats config.yaml build --nolock
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job build since they might be corrupted:
twofoo/bcalm.twofoo.k31.unitigs.fa
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/jessicamizzi/spacegraphcats-twofoo-example/.snakemake/log/2020-06-23T101113.247872.snakemake.log
```
Log file:
```
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all
        1       build
        1       download_akker
        1       download_shew
        1       extract
        1       make_twofoo
        1       search
        7

[Tue Jun 23 10:11:14 2020]
rule download_akker:
    output: data/akker-reads.abundtrim.gz
    jobid: 6

[Tue Jun 23 10:11:21 2020]
Finished job 6.
1 of 7 steps (14%) done

[Tue Jun 23 10:11:21 2020]
rule download_shew:
    output: data/shew-reads.abundtrim.gz
    jobid: 5

[Tue Jun 23 10:11:26 2020]
Finished job 5.
2 of 7 steps (29%) done

[Tue Jun 23 10:11:26 2020]
rule make_twofoo:
    input: data/shew-reads.abundtrim.gz, data/akker-reads.abundtrim.gz
    output: data/twofoo.fq.gz
    jobid: 4

[Tue Jun 23 10:14:45 2020]
Finished job 4.
3 of 7 steps (43%) done

[Tue Jun 23 10:14:45 2020]
rule build:
    input: data/twofoo.fq.gz
    output: twofoo/bcalm.twofoo.k31.unitigs.fa, twofoo_k31_r1/catlas.csv, twofoo_k31_r1/cdbg.gxt, twofoo_k31_r1/contigs.fa.gz, twofoo_k31_r1/contigs.fa.gz.indices, twofoo_k31_r1/contigs.fa.gz.info.csv, twofoo_k31_r1/contigs.fa.gz.mphf, twofoo_k31_r1/first_doms.txt
    jobid: 3

[Tue Jun 23 10:16:20 2020]
Error in rule build:
    jobid: 3
    output: twofoo/bcalm.twofoo.k31.unitigs.fa, twofoo_k31_r1/catlas.csv, twofoo_k31_r1/cdbg.gxt, twofoo_k31_r1/contigs.fa.gz, twofoo_k31_r1/contigs.fa.gz.indices, twofoo_k31_r1/contigs.fa.gz.info.csv, twofoo_k31_r1/contigs.fa.gz.mphf, twofoo_k31_r1/first_doms.txt
    shell:
        /Users/jessicamizzi/software/miniconda3/envs/sgc/bin/python3.7 -m spacegraphcats config.yaml build --nolock
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job build since they might be corrupted:
twofoo/bcalm.twofoo.k31.unitigs.fa
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/jessicamizzi/spacegraphcats-twofoo-example/.snakemake/log/2020-06-23T101113.247872.snakemake.log
```

@taylorreiter thanks for the ram suggestion! I'm running this on my local laptop. How much ram would you recommend to run twofoo and how should I specify that? (apologies if this is easily google-able!)

**Comment by ctb** [comment]
ugh. this is on your laptop, which is Mac OS X?

could you drop in the output of 'conda env export' pls? (when you're
in the relevant env)?

--t

**Comment by jessicamizzi** [comment]
It is on my laptop, which is Mac OS Catalina 10.15.4.

`conda env export output` when I'm in sgc:

```
name: sgc
channels:
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - appdirs=1.4.3=py_1
  - attrs=19.3.0=py_0
  - bcalm=2.2.1=hd28b015_0
  - brotlipy=0.7.0=py37h9bfed18_1000
  - bz2file=0.98=py_0
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py37hc8dfbb8_0
  - cffi=1.14.0=py37h356ff06_0
  - chardet=3.0.4=py37hc8dfbb8_1006
  - configargparse=1.2.3=pyh9f0ad1d_0
  - cryptography=2.9.2=py37he655712_0
  - cycler=0.10.0=py_2
  - cython=0.29.14=py37h4a8c4bd_0
  - datrie=0.8.2=py37h9bfed18_0
  - docutils=0.16=py37hc8dfbb8_1
  - freetype=2.10.2=h8da9a1a_0
  - gitdb=4.0.5=py_0
  - gitpython=3.1.3=py_0
  - idna=2.9=py_1
  - importlib-metadata=1.6.1=py37hc8dfbb8_0
  - importlib_metadata=1.6.1=0
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - khmer=3.0.0a3=py37h0a44026_0
  - kiwisolver=1.2.0=py37ha1cc60f_0
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libcxx=10.0.0=h1af66ff_2
  - libffi=3.2.1=h4a8c4bd_1007
  - libgfortran=4.0.0=2
  - liblapack=3.8.0=16_openblas
  - libopenblas=0.3.9=h3d69b6c_0
  - libpng=1.6.37=hbbe82c9_1
  - llvm-openmp=10.0.0=h28b9765_0
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py37hddda452_0
  - more-itertools=8.4.0=py_0
  - mypy=0.750=py_0
  - mypy_extensions=0.4.3=py37hc8dfbb8_1
  - ncurses=6.1=h0a44026_1002
  - numpy=1.17.3=py37hde6bac1_0
  - openssl=1.1.1g=h0b31af3_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=0.25.3=py37h4f17bb1_0
  - pip=20.1.1=py_1
  - pluggy=0.13.1=py37hc8dfbb8_2
  - psutil=5.7.0=py37h9bfed18_1
  - py=1.8.2=pyh9f0ad1d_0
  - pycparser=2.20=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.16.0=py37h9bfed18_0
  - pysocks=1.7.1=py37hc8dfbb8_1
  - pytest=5.3.2=py37_0
  - python=3.7.6=cpython_h1fd5dd1_6
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=pyh9f0ad1d_0
  - pyyaml=5.3.1=py37h9bfed18_0
  - ratelimiter=1.2.0=py37hc8dfbb8_1001
  - readline=8.0=hcfe32e1_0
  - requests=2.24.0=pyh9f0ad1d_0
  - scipy=1.4.1=py37hce1b9e5_3
  - screed=1.0.1=py_0
  - setuptools=47.3.1=py37hc8dfbb8_0
  - six=1.15.0=pyh9f0ad1d_0
  - smmap=3.0.4=pyh9f0ad1d_0
  - snakemake-minimal=5.8.1=py_0
  - sortedcontainers=2.1.0=py_0
  - sourmash=2.3.0=py37h6de7cb9_0
  - sqlite=3.30.1=h93121df_0
  - tk=8.6.10=hbbe82c9_0
  - tornado=6.0.4=py37h9bfed18_1
  - typed-ast=1.4.1=py37h0b31af3_0
  - typing_extensions=3.7.4.2=py_0
  - urllib3=1.25.9=py_0
  - wcwidth=0.2.4=pyh9f0ad1d_0
  - wheel=0.34.2=py_1
  - wrapt=1.12.1=py37h9bfed18_1
  - xz=5.2.5=h0b31af3_0
  - yajl=2.1.0=0
  - yaml=0.2.5=h0b31af3_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h0b31af3_1006
  - pip:
    - bbhash==0.2
    - ijson==3.0.4
    - spacegraphcats==1.2.dev26+g6ad95ec
prefix: /Users/jessicamizzi/software/miniconda3/envs/sgc
```

**Comment by ctb** [comment]
wow, this is weird. I got it running just fine on my mac, and my environment is (basically) the same as yours -- here's the diff:

```
83c83
<   - wcwidth=0.2.5=pyh9f0ad1d_0
---
>   - wcwidth=0.2.4=pyh9f0ad1d_0
95,96c95
< prefix: /Users/t/miniconda3/envs/sgc-test
< 
---
> prefix: /Users/jessicamizzi/software/miniconda3/envs/sgc
```
I'm on mojave, 10.14.6. I hope that doesn't make the difference...

oh, one thought -- could you `rm twofoo/bcalm.twofoo.k31.unitigs.fa` and try rerunning?

**Comment by jessicamizzi** [comment]
Hmm I wonder if I have some strange setting on my computer from messing with things at some point? Weird!

Also, I git cloned the [spacegraphcats](https://github.com/spacegraphcats/spacegraphcats) repo and also the [spacegraphcats-twofoo-example](https://github.com/spacegraphcats/spacegraphcats-twofoo-example) repo, they are both in my home directory. I'm currently working in spacegraphcats-twofoo-example. When I run `ls twofoo` I get `bcalm.twofoo.k31.inputlist.txt` and `bcalm.twofoo.k31.unitigs.fa.log.txt` as the only files shown.

**Comment by ctb** [comment]
On Wed, Jun 24, 2020 at 09:59:43AM -0700, jessicamizzi wrote:
> Hmm I wonder if I have some strange setting on my computer from messing with things at some point? Weird!

no... shouldn't be...

> Also, I git cloned the [spacegraphcats](https://github.com/spacegraphcats/spacegraphcats) repo and also the [spacegraphcats-twofoo-example](https://github.com/spacegraphcats/spacegraphcats-twofoo-example) repo, they are both in my home directory. I'm currently working in spacegraphcats-twofoo-example. When I run `ls twofoo` I get `bcalm.twofoo.k31.inputlist.txt` and `bcalm.twofoo.k31.unitigs.fa.log.txt` as the only files shown.

well that's weird...

do:

rm twofoo_k31_r1/contigs.fa.gz

Or better,

rm data/twofoo.fq.gz

and then snakemake.

thx,
--t

**Comment by jessicamizzi** [comment]
`ls twofoo_k31_r1` only shows `bcalm_to_gxt.log` and `ls data` only shows `akker-reads.abundtrim.gz` and `shew-reads.abundtrim.gz` (I'm in the spacegraphcats/spacegraphcats-twofoo-example repo, should I be in spacegraphcats/spacegraphcats?)

I just reran snakemake and at the end I get the message
```
Removing output files of failed job build since they might be corrupted:
twofoo/bcalm.twofoo.k31.unitigs.fa
```
so it looks like that file is being removed.

**Comment by ctb** [comment]
huh. ok. it's doing things properly then.

two last requests - could you try this on your linux compute server, pls? and could you send me (privately is fine) a screenshot of your laptop's "about this mac" window, under your apple menu on the upper left?

**Comment by ctb** [comment]
I can replicate now on my upgraded mac - https://github.com/spacegraphcats/spacegraphcats/pull/281 - so it might be a problem specific to Catalina, or new hardware, or something.

**Comment by ctb** [comment]
FYI, fixed by #281!!

**Comment by ctb** [comment]
(@jessicamizzi this would require creating a new conda environment on your mac)

**Comment by jessicamizzi** [comment]
Thank you!!!
