### ISSUE TITLE
Restart spacegraphcats that failed to finish in allotted walltime?

### ISSUE THREAD

**Issue by jwsorens** [spacegraphcats/spacegraphcats#298]
I'm currently trying to use sgc on a soil metagenome, but am running into a couple of issues. I have gotten both the two-foo and dory test examples to work properly. I recently submitted a sgc job but it failed to finish in the allotted wall time, the output is below. 
```
Found configfile at /share/emersonlab/sorensen/spacegraphcats/spacegraphcats/./conf/RR.json
--------
details!
	snakefile: /share/emersonlab/sorensen/spacegraphcats/spacegraphcats/./conf/Snakefile
	config: /share/emersonlab/sorensen/spacegraphcats/spacegraphcats/./conf/RR.json
	targets: ['search']
--------
...sgc is updating input file data/RR/RR452Oct_Bulk_S26_abundtrim.fq.gz with outdir prefix /share/emersonlab/sorensen/spacegraphcats
...sgc is updating input file data/RR/HQRR.18.fa with outdir prefix /share/emersonlab/sorensen/spacegraphcats
...sgc is updating input file data/RR/HQRR.25.fa with outdir prefix /share/emersonlab/sorensen/spacegraphcats
...sgc is updating input file data/RR/LQRR.84.fa with outdir prefix /share/emersonlab/sorensen/spacegraphcats
...sgc is updating input file data/RR/LQRR.8.fa with outdir prefix /share/emersonlab/sorensen/spacegraphcats
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	bcalm_catlas_input
	1	bcalm_cdbg
	1	build_catlas
	1	make_contigs_kmer_index
	1	search
	5

[Mon Sep 28 17:32:06 2020]
rule bcalm_cdbg:
    input: RR_test/bcalm.RR_test.k21.inputlist.txt
    output: RR_test/bcalm.RR_test.k21.unitigs.fa
    jobid: 4
    wildcards: catlas_base=RR_test, ksize=21

(bcalm >& /dev/null || (printf '**\n**\n** Cannot run BCALM 2! Please install it and make sure it is on your path!\n**\n**\n'; exit 1)) && (bcalm >& /dev/null && bcalm -in RR_test/bcalm.RR_test.k21.inputlist.txt -out RR_test/bcalm.RR_test.k21 -kmer-size 21 -abundance-min 1 >& RR_test/bcalm.RR_test.k21.unitigs.fa.log.txt && rm -f RR_test/bcalm.RR_test.k21.{h5,unitigs.fa.glue*} || printf '\n**\n** ERROR running BCALM 2; err output in dory/bcalm.dory.k21.unitigs.fa.log.txt\n**\n')
[Tue Sep 29 12:59:45 2020]
Finished job 4.
1 of 5 steps (20%) done

[Tue Sep 29 12:59:45 2020]
rule bcalm_catlas_input:
    input: RR_test/bcalm.RR_test.k21.unitigs.fa
    output: RR_test_k21_r1/cdbg.gxt, RR_test_k21_r1/contigs.fa.gz, RR_test_k21_r1/contigs.fa.gz.info.csv
    jobid: 3

/share/emersonlab/sorensen/anaconda2/envs/sgc/bin/python -m spacegraphcats.cdbg.bcalm_to_gxt  -k 21 RR_test/bcalm.RR_test.k21.unitigs.fa RR_test_k21_r1/cdbg.gxt RR_test_k21_r1/contigs.fa.gz
Auks API request failed : auks cred : credential expired
slurmstepd: error: *** JOB 27623710 ON fleet-28 CANCELLED AT 2020-09-30T18:32:31 DUE TO TIME LIMIT ***
```

When I try to re-run the job using the same code, the output is as follows. 
```
Found configfile at /share/emersonlab/sorensen/spacegraphcats/spacegraphcats/./conf/RR.json
--------
details!
	snakefile: /share/emersonlab/sorensen/spacegraphcats/spacegraphcats/./conf/Snakefile
	config: /share/emersonlab/sorensen/spacegraphcats/spacegraphcats/./conf/RR.json
	targets: ['search']
--------
...sgc is updating input file data/RR/RR452Oct_Bulk_S26_abundtrim.fq.gz with outdir prefix /share/emersonlab/sorensen/spacegraphcats
...sgc is updating input file data/RR/HQRR.18.fa with outdir prefix /share/emersonlab/sorensen/spacegraphcats
...sgc is updating input file data/RR/HQRR.25.fa with outdir prefix /share/emersonlab/sorensen/spacegraphcats
...sgc is updating input file data/RR/LQRR.84.fa with outdir prefix /share/emersonlab/sorensen/spacegraphcats
...sgc is updating input file data/RR/LQRR.8.fa with outdir prefix /share/emersonlab/sorensen/spacegraphcats
Building DAG of jobs...
IncompleteFilesException:
The files below seem to be incomplete. If you are sure that certain files are not incomplete, mark them as complete with

    snakemake --cleanup-metadata <filenames>

To re-generate the files rerun your command with the --rerun-incomplete flag.
Incomplete files:
RR_test_k21_r1/cdbg.gxt
RR_test_k21_r1/contigs.fa.gz
RR_test_k21_r1/contigs.fa.gz.info.csv
```
Those files are indeed incomplete but when I try to add a `--rerun-incomplete` flag I get a `__main__.py: error: unrecognized arguments: --rerun-incomplete`. Is there a way to specify this flag in the configuration file or directly in the simple command?

**Comment by ctb** [comment]
yes! see https://github.com/spacegraphcats/spacegraphcats/issues/272 - you should be able to run something like `python -m spacegraphcats.click conf/RR.json --rerun-incomplete`.

**Comment by ctb** [comment]
(I'm in the middle of something so can't test, lmk if it works/doesn't work :)

**Comment by jwsorens** [comment]
Just ran `python -m spacegraphcats.click conf/RR.json --rerun-incomplete` and got the following error. 
```
Traceback (most recent call last):
  File "/share/emersonlab/sorensen/anaconda2/envs/sgc/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/share/emersonlab/sorensen/anaconda2/envs/sgc/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/share/emersonlab/sorensen/spacegraphcats/spacegraphcats/click.py", line 7, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```
Installation fault on my end?

**Comment by ctb** [comment]
On Thu, Oct 01, 2020 at 05:59:07PM +0000, jwsorens wrote:
> Just ran `python -m spacegraphcats.click conf/RR.json --rerun-incomplete` and got the following error. 
> ```
> Traceback (most recent call last):
>   File "/share/emersonlab/sorensen/anaconda2/envs/sgc/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/share/emersonlab/sorensen/anaconda2/envs/sgc/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/share/emersonlab/sorensen/spacegraphcats/spacegraphcats/click.py", line 7, in <module>
>     import click
> ModuleNotFoundError: No module named 'click'
> ```
> Installation fault on my end? 

nope. My fault.

run,

pip install click

and retry :).

**Comment by jwsorens** [comment]
Had to unlock the directory but then that did it. Thanks for the quick response!

**Comment by ctb** [comment]
yay!!!

**Comment by ctb** [comment]
I'll fix the install stuff sooner or later. glad the click approach worked! pls go ahead and close this issue if it's all working out so far!
