### ISSUE TITLE
how are paired reads labelled?

### ISSUE THREAD

**Issue by taylorreiter** [spacegraphcats/spacegraphcats#383]
Messing with sgc `v2.0b12.dev1+g484608f`

I ran two-foo with:
```
git clone https://github.com/spacegraphcats/spacegraphcats-twofoo-example.git
cd spacegraphcats-twofoo-example
snakemake -j 1 --until make_twofoo

python -m spacegraphcats run config.yaml extract_contigs extract_reads --nolock
```

Then I tried to extract the paired reads
```
cd twofoo_k31_r1_search_oh0
extract-paired-reads.py -d test_paired_63 63.fa.gz.cdbg_ids.reads.gz
```

Which produces the error:

```
|| This is the script extract-paired-reads.py in khmer.
|| You are running khmer version 3.0.0a3
|| You are also using screed version 1.0.1
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2015. https://doi.org/10.12688/f1000research.6924.1
||
|| Please see http://khmer.readthedocs.io/en/latest/citations.html for details.

reading file "63.fa.gz.cdbg_ids.reads.gz"
outputting interleaved pairs to "test_paired_63/63.fa.gz.cdbg_ids.reads.gz.pe"
outputting orphans to "test_paired_63/63.fa.gz.cdbg_ids.reads.gz.se"
... 100000
... 200000
... 300000
... 400000
... 500000
... 600000
... 700000
... 800000
Traceback (most recent call last):
  File "/home/tereiter/miniconda3/envs/sgc_latest/bin/extract-paired-reads.py", line 181, in <module>
    main()
  File "/home/tereiter/miniconda3/envs/sgc_latest/bin/extract-paired-reads.py", line 170, in main
    raise Exception("no paired reads!? check file formats...")
Exception: no paired reads!? check file formats...
```

but when I look at the file `twofoo_k31_r1_search_oh0/63.fa.gz.cdbg_ids.reads.gz`, I see that there are some paired reads, e.g. the last two reads here are paired (I think):

```
>SRR606249.289484
GCTAAATGCTAAATGCTAAATGCTAAATGCTAAATGCTAAATGCTAAATGCTAAATGCTAAATGCTAAATGCTAAATGCTAAATGCTAAATGCTAAATGCT
>SRR606249.785274
TCATAGTGATCCGGTGGTTCTGAATGGAAGGGCCATCGCTCAACGGATAAAAGGTACTCCGGGGATAACAGGCTGATACCGCCCAAGAGTTCATATCGACG
>SRR606249.818009
AACTGGAGCATCGACTTAACCGGCACCACCTTGGCCGATGGCACTTACCCTGTCAGCGCCACGGTCACTGACCTGGCGGGCAACAGCAAGACCGTCACCCA
>SRR606249.937276
GCAACACCGTGGCGATCACCAGCATTACCGATGACACCGGCGCCTCGGGCAGCGACTTCATCACCAACGACAACACCTTAGTGTTCAACGGTACCGTCGAT
>SRR606249.985492
GGGACCGACTTCAGCCCCAGGATGTGATGAGCCGACATCGAGGTGCCAAACACCGCCGTCGATATGAACTCTTGGGCGGTATCAGCCTGTTATCCCCGGAG
>SRR606249.989382
CGAACAGCCATACCCTTGGGACCGGCTACAGCCCCAGGATGAGATGAGCCGACATCGAGGTGCCAAACACCGCCGTCGATATGAACTCTTGGGCGGTATCA
>SRR606249.1005551
CGATTTAGGTGACAACAGCACCTTGGCCGTCACCATCAATGGCGTGGT
>SRR606249.1017239
CGTCACCATCAATGGCGTGGTCTACACCACTGCCAACGGCTTGGTGATTGATGCCAGCGGTAACTGGAGCATCGACTTAACCGGCACCACCTTGGCCGATG
>SRR606249.1024714
CAACAGCACCTTGGCCGTCACCATCAATGGCGTGGTCTACACCACCGCCAACGGCTTGGTGATTGATGCCAGCGGTAACTGGAGCATCGACTTAACCGGCA
>SRR606249.1032421
ATCCGCTGCTCTGTTCTTCCATGCCCTTTTTCCGAACAGGCAAATTGGGCTAACTGACTGTCATCTTGGAAGGCCACATCATACTGCGCTTTAACTGCTTG
>SRR606249.1044514
CACCGCCGTCGATATGAACTCTTGGGCGGTATCAGCCTGTTATCCCCGGAGTACCTTTTATCCGTTGAGCGATGGCCCTTCCATTCAGAACCACCGGATCA
>SRR606249.1044514
TAACAGGCTGATACCGCCCAAGAGTTCATATCGACGGCGGTGTTTGGCACCTCGATGTCGGCTCATCACATCCTGGGGCTGAAGTCGGTCCCAAGGGTATG
```

So it seems to me that paired reads are currently not labelled? Can we label reads are R1/R2? I think this might be necessary to used paired in modes of downstream tools such as megahit.

**Comment by ctb** [comment]
done by genome-grist, [here](https://github.com/dib-lab/genome-grist/blob/latest/genome_grist/conf/Snakefile#L232)

**Comment by taylorreiter** [comment]
Ok so the fact that the sgc output is difficult to split into R1/R2/unpaired in this example has nothing to do with sgc, and instead has to do with the way the twofoo reads were first generated/labelled, where I assume they are missing the `.1` and `.2` designations after genome-grist downloading them?

**Comment by ctb** [comment]
On Wed, Feb 17, 2021 at 12:16:08PM -0800, Taylor Reiter wrote:
> Ok so the fact that the sgc output is difficult to split into R1/R2/unpaired in this example has nothing to do with sgc, and instead has to do with the way the twofoo reads were first generated/labelled, where I assume they are missing the `.1` and `.2` designations after genome-grist downloading them?

yes, I think so.

**Comment by ctb** [comment]
note to self: we could provide this guidance somewhere, along with info on how to fix the naming scheme.
