### ISSUE TITLE
FileIO and TextIOWrapper warnings in `bcalm_catlas_prepare_input`

### ISSUE THREAD

**Issue by taylorreiter** [spacegraphcats/spacegraphcats#400]
Not sure if this matters, catlas still built 

```
rule bcalm_catlas_prepare_input:
    input: rgnv_nbhd_diginorm_hardtrim2_k31/bcalm.unitigs.fa, rgnv_nbhd_diginorm_hardtrim2_k31/bcalm.unitigs.predb, rgnv_nbhd_diginorm_hardtrim2_k31/bcalm.unitigs.pickle
    output: rgnv_nbhd_diginorm_hardtrim2_k31_r12/cdbg.gxt, rgnv_nbhd_diginorm_hardtrim2_k31_r12/contigs.info.csv, rgnv_nbhd_diginorm_hardtrim2_k31_r12/contigs.sig, rgnv_nbhd_diginorm_hardtrim2_k31/bcalm.unitigs.db
    jobid: 2


This is spacegraphcats 2.0b12.dev7+gc495b99.

Job counts:
        count   jobs
        1       bcalm_catlas_prepare_input
        1
Found 2069260 input unitigs.
removing pendants...
...removed 4507 nodes.
calculating sourmash signature of output unitigs
Outputting graph information to 'rgnv_nbhd_diginorm_hardtrim2_k31_r12/cdbg.gxt'...
...done! 2064753 vertices, 4781836 edges
Exception ignored in: <_io.FileIO name='rgnv_nbhd_diginorm_hardtrim2_k31_r12/contigs.sig' mode='wb' closefd=True>
Traceback (most recent call last):
  File "/home/tereiter/github/spacegraphcats/spacegraphcats/cdbg/bcalm_to_gxt2.py", line 310, in main
    sourmash.save_signatures([out_sig], open(args.contigs_prefix + ".sig", "wt"))
ResourceWarning: unclosed file <_io.TextIOWrapper name='rgnv_nbhd_diginorm_hardtrim2_k31_r12/contigs.sig' mode='wt' encoding='UTF-8'>
Exception ignored in: <_io.FileIO name='rgnv_nbhd_diginorm_hardtrim2_k31_r12/cdbg.gxt' mode='wb' closefd=True>
Traceback (most recent call last):
  File "/home/tereiter/github/spacegraphcats/spacegraphcats/cdbg/bcalm_to_gxt2.py", line 318, in <module>
    main(sys.argv[1:])
ResourceWarning: unclosed file <_io.TextIOWrapper name='rgnv_nbhd_diginorm_hardtrim2_k31_r12/cdbg.gxt' mode='wt' encoding='UTF-8'>
Exception ignored in: <_io.FileIO name='rgnv_nbhd_diginorm_hardtrim2_k31_r12/contigs.info.csv' mode='wb' closefd=True>
Traceback (most recent call last):
  File "/home/tereiter/github/spacegraphcats/spacegraphcats/cdbg/bcalm_to_gxt2.py", line 318, in <module>
    main(sys.argv[1:])
ResourceWarning: unclosed file <_io.TextIOWrapper name='rgnv_nbhd_diginorm_hardtrim2_k31_r12/contigs.info.csv' mode='wt' encoding='UTF-8'>
```

**Comment by ctb** [comment]
hah, thanks, saw that earlier myself. thanks for filing the issue!
