### ISSUE TITLE
AttributeError: 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by maureenbug** [spacegraphcats/spacegraphcats#471]
Hi!

I was getting some (sudden) random errors running spacegraphcats, so I did a fresh install of sgc to see if the error would go away. I got a new error:

python version is 3.8.15
I installed sgc with conda following the instructions on the website

(/global/cscratch1/sd/mberg/spacegraphcats) mberg@cori12:/global/cscratch1/sd/mberg/full_soil_pipeline_w_new_assembly/sgc_output_files/early_sgc_out> spacegraphcats search /global/cscratch1/sd/mberg/full_soil_pipeline_w_new_assembly/sgc_output_files/early_sgc_out/viral_config.yaml extract_reads

This is spacegraphcats 2.1.2.dev0+g514d9ed.d20221201.

Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Traceback (most recent call last):
  File "/global/cscratch1/sd/mberg/spacegraphcats/lib/python3.8/site-packages/snakemake/__init__.py", line 722, in snakemake
    success = workflow.execute(
  File "/global/cscratch1/sd/mberg/spacegraphcats/lib/python3.8/site-packages/snakemake/workflow.py", line 1092, in execute
    logger.run_info("\n".join(dag.stats()))
  File "/global/cscratch1/sd/mberg/spacegraphcats/lib/python3.8/site-packages/snakemake/dag.py", line 2248, in stats
    yield tabulate(rows, headers="keys")
  File "/global/cscratch1/sd/mberg/spacegraphcats/lib/python3.8/site-packages/tabulate/__init__.py", line 2048, in tabulate
    list_of_lists, headers = _normalize_tabular_data(
  File "/global/cscratch1/sd/mberg/spacegraphcats/lib/python3.8/site-packages/tabulate/__init__.py", line 1471, in _normalize_tabular_data
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/global/cscratch1/sd/mberg/spacegraphcats/lib/python3.8/site-packages/tabulate/__init__.py", line 1471, in <lambda>
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/global/cscratch1/sd/mberg/spacegraphcats/lib/python3.8/site-packages/tabulate/__init__.py", line 107, in _is_separating_line
    (len(row) >= 1 and row[0] == SEPARATING_LINE)
  File "/global/cscratch1/sd/mberg/spacegraphcats/lib/python3.8/site-packages/snakemake/rules.py", line 1215, in __eq__
    return self.name == other.name and self.output == other.output
AttributeError: 'str' object has no attribute 'name'
Error in snakemake invocation: Command '['snakemake', '-s', '/global/cscratch1/sd/mberg/spacegraphcats/spacegraphcats/conf/Snakefile', '--use-conda', '-j', '1', 'search', 'extract_reads', '--configfile', '/global/cscratch1/sd/mberg/spacegraphcats/spacegraphcats/conf/defaults.conf', '/global/cscratch1/sd/mberg/full_soil_pipeline_w_new_assembly/sgc_output_files/early_sgc_out/viral_config.yaml']' returned non-zero exit status 1.

any help is appreciated!

**Comment by taylorreiter** [comment]
if you bump the version of snakemake it should disappear, so:

```
conda install snakemake-minimal=7.18.2
```

in whatever your conda env is for sgc! please let us know if this fixes the problem :)

**Comment by maureenbug** [comment]
Thanks taylor! I did that but got this error

Traceback (most recent call last):
  File "/global/cscratch1/sd/mberg/spacegraphcats/lib/python3.8/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/global/cscratch1/sd/mberg/spacegraphcats/lib/python3.8/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/global/cscratch1/sd/mberg/spacegraphcats/lib/python3.8/site-packages/pkg_resources/__init__.py", line 800, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (snakemake 7.18.2 (/global/cscratch1/sd/mberg/spacegraphcats/lib/python3.8/site-packages), Requirement.parse('snakemake==7.3.8'), {'spacegraphcats'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/cscratch1/sd/mberg/spacegraphcats/bin/spacegraphcats", line 33, in <module>
    sys.exit(load_entry_point('spacegraphcats', 'console_scripts', 'spacegraphcats')())
  File "/global/cscratch1/sd/mberg/spacegraphcats/bin/spacegraphcats", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/global/cscratch1/sd/mberg/spacegraphcats/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/global/cscratch1/sd/mberg/spacegraphcats/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/global/cscratch1/sd/mberg/spacegraphcats/spacegraphcats/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
  File "/global/cscratch1/sd/mberg/spacegraphcats/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/global/cscratch1/sd/mberg/spacegraphcats/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/global/cscratch1/sd/mberg/spacegraphcats/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/global/cscratch1/sd/mberg/spacegraphcats/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/global/cscratch1/sd/mberg/spacegraphcats/lib/python3.8/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/global/cscratch1/sd/mberg/spacegraphcats/lib/python3.8/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'snakemake==7.3.8' distribution was not found and is required by spacegraphcats




is this just some path issue or?

**Comment by taylorreiter** [comment]
sort of yes -- the sgc package is checking if the right version of snakemake is installed, and not getting the right one. I didn't think it would do that, sorry! @ctb, would changing https://github.com/spacegraphcats/spacegraphcats/blob/latest/requirements.txt#L6 to the updated version of snakemake fix this new issue?

**Comment by ctb** [comment]
see understanding and resolution here: https://github.com/dib-lab/genome-grist/issues/237#issuecomment-1336256533

will fix spacegraphcats shortly!

**Comment by ctb** [comment]
Fixed by https://github.com/spacegraphcats/spacegraphcats/pull/479 and https://github.com/spacegraphcats/spacegraphcats/pull/476. Preventative measures added in https://github.com/spacegraphcats/spacegraphcats/pull/472 ;).

Latest spacegraphcats release v2.1.2 contains these fixes (tl;dr update version of snakemake).

Thank you for reporting!!

**Comment by maureenbug** [comment]
just writing an update that it works perfectly on my end now, tysm!!

**Comment by ctb** [comment]
very much appreciated - thanks!
