### ISSUE TITLE
Error in make_contigs_kmer_index: ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by taylorreiter** [spacegraphcats/spacegraphcats#507]
input sequence -- human transcriptome
```
curl -JLO https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.40_GRCh38.p14/GCF_000001405.40_GRCh38.p14_rna.fna.gz
```

command run: 
```
python -m spacegraphcats run outputs/sgc_conf/sgc_k151_conf.yml extract_reads --nolock --outdir=outputs/sgc_human/ --rerun-incomplete
```
conf file (`NM_001350175.2` could be any transcript in the transcriptome; i'm trying to query with one isoform and retrieve all of the others w/o off target transcripts being retrieved as well)
```
catlas_base: GCF_000001405.40_GRCh38.p14_rna
input_sequences:
- inputs/GCF_000001405.40_GRCh38.p14_rna.fna.gz
ksize: 151
radius: 1
paired_reads: false
keep_graph_pendants: true
search:
- NM_001350175.2.fa
```

Last few lines of the stdout 
```
Computing low degree orientation (step 1)
bucketed 130 of 130 nodes
removed 130 of 130 nodes
assigning to dominators
computing domgraph edges
Catlas level 51 complete
catlas built
writing graph
fatal: not a git repository (or any of the parent directories): .git
[Wed Oct 25 09:42:53 2023]
Finished job 10.
5 of 1009 steps (0.5%) done
Select jobs to execute...

[Wed Oct 25 09:42:53 2023]
rule make_contigs_kmer_index:
    input: GCF_000001405.40_GRCh38.p14_rna_k151/bcalm.unitigs.db
    output: GCF_000001405.40_GRCh38.p14_rna_k151/contigs.mphf, GCF_000001405.40_GRCh38.p14_rna_k151/contigs.indices, GCF_000001405.40_GRCh38.p14_rna_k151/contigs.sizes
    jobid: 4
    reason: Missing output files: GCF_000001405.40_GRCh38.p14_rna_k151/contigs.mphf, GCF_000001405.40_GRCh38.p14_rna_k151/contigs.indices; Input files updated by another job: GCF_000001405.40_GRCh38.p14_rna_k151/bcalm.unitigs.db
    resources: tmpdir=/var/folders/76/q53ldgh1667_lm49fpxybglc0000gn/T

This is spacegraphcats 2.1.3.dev13+g08ba7c0.

Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Select jobs to execute...
Changing to shadow directory: /Users/taylorreiter/github/2023-sgc-for-isoform-collapse/outputs/sgc_human/.snakemake/shadow/tmprdj8iszi
reading cDBG nodes from sqlite DB GCF_000001405.40_GRCh38.p14_rna_k151/bcalm.unitigs.db
loaded 324405 contigs.

NOTE: no multicount hashvals detected.
building MPHF for 0 k-mers in 324405 nodes.
second pass.
reading cDBG nodes from sqlite DB GCF_000001405.40_GRCh38.p14_rna_k151/bcalm.unitigs.db
loaded 324405 contigs in pass2.

Traceback (most recent call last):
  File "/Users/taylorreiter/github/2023-sgc-for-isoform-collapse/.snakemake/conda/64aeb6a3434c573f813a37cd3eb95c7a_/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/taylorreiter/github/2023-sgc-for-isoform-collapse/.snakemake/conda/64aeb6a3434c573f813a37cd3eb95c7a_/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/taylorreiter/github/2023-sgc-for-isoform-collapse/.snakemake/conda/64aeb6a3434c573f813a37cd3eb95c7a_/lib/python3.8/site-packages/spacegraphcats/cdbg/index_cdbg_by_kmer.py", line 143, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/taylorreiter/github/2023-sgc-for-isoform-collapse/.snakemake/conda/64aeb6a3434c573f813a37cd3eb95c7a_/lib/python3.8/site-packages/spacegraphcats/cdbg/index_cdbg_by_kmer.py", line 133, in main
    table, sizes = build_mphf(args.ksize, create_records_iter)
  File "/Users/taylorreiter/github/2023-sgc-for-isoform-collapse/.snakemake/conda/64aeb6a3434c573f813a37cd3eb95c7a_/lib/python3.8/site-packages/spacegraphcats/cdbg/index_cdbg_by_kmer.py", line 106, in build_mphf
    max_table_value = max(table.mphf_to_value)
ValueError: max() arg is an empty sequence
[Wed Oct 25 09:42:56 2023]
Error in rule make_contigs_kmer_index:
    jobid: 0
    input: GCF_000001405.40_GRCh38.p14_rna_k151/bcalm.unitigs.db
    output: GCF_000001405.40_GRCh38.p14_rna_k151/contigs.mphf, GCF_000001405.40_GRCh38.p14_rna_k151/contigs.indices, GCF_000001405.40_GRCh38.p14_rna_k151/contigs.sizes
    shell:

        python -Werror -Wignore::DeprecationWarning -m spacegraphcats.cdbg.index_cdbg_by_kmer             -k 151 GCF_000001405.40_GRCh38.p14_rna_k151 --contigs-db GCF_000001405.40_GRCh38.p14_rna_k151/bcalm.unitigs.db

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: ../../.snakemake/log/2023-10-25T090551.883451.snakemake.log
Error in snakemake invocation: Command '['snakemake', '-s', '/Users/taylorreiter/github/2023-sgc-for-isoform-collapse/.snakemake/conda/64aeb6a3434c573f813a37cd3eb95c7a_/lib/python3.8/site-packages/spacegraphcats/conf/Snakefile', '--use-conda', '--config', 'outdir=outputs/sgc_human/', '-j', '1', 'extract_reads', '--nolock', '--rerun-incomplete', '--configfile', '/Users/taylorreiter/github/2023-sgc-for-isoform-collapse/.snakemake/conda/64aeb6a3434c573f813a37cd3eb95c7a_/lib/python3.8/site-packages/spacegraphcats/conf/defaults.conf', 'outputs/sgc_conf/sgc_k151_conf.yml']' returned non-zero exit status 1.
```

Context -- My snakefile & sgc code works just fine for k-mers size 31-121, but I start have issues at 131. 
The shortest contig in the transcriptome is 33bp, so I don't think that is causing issues here given that k-mer lengths 41-121 worked just fine.

I'm less concerned with fixing this error and more curious about why it's happening 🤷‍♀️

**Comment by taylorreiter** [comment]
I think a value in the bbhash table is unset?
https://github.com/spacegraphcats/spacegraphcats/blob/latest/spacegraphcats/cdbg/index_cdbg_by_kmer.py#L106

wondering if pybbhash/bbhash have a max k-mer value. I went looking in the bbhash paper and the github repos of bbhash and pybbhash but couldn't find that value (reported as such -- lots of info on bits that I might be missing something from)
