### ISSUE TITLE
`ModuleNotFoundError: No module named 'Cython'` error when install sgc on EC2 instance

### ISSUE THREAD

**Issue by jessicalumian** [spacegraphcats/spacegraphcats#511]
hi! I'm having problems installing sgc on a fresh ec2. This could be user error.

AMI: Ubuntu Server 20.04 LTS (HVM), SSD Volume Type
Instance Type: r4.large

Followed installs here: https://spacegraphcats.github.io/spacegraphcats/00-installing-spacegraphcats/ and then here: https://github.com/GATB/bcalm#installation when bcalm is mentioned

Code ran:
```
sudo apt-get update
sudo apt-get -y install python3 python3-dev zlib1g-dev g++ \
    python3-venv make cmake

python3 -m venv catsenv
. catsenv/bin/activate
pip install -U setuptools pip
pip install Cython
```

Next doing bcalm install:
```
git clone --recursive https://github.com/GATB/bcalm 
cd bcalm
mkdir build;  cd build;  cmake ..;  make -j 8
```

Now cloning spg repo inside bcalm repo (would that cause a problem?)
```
git clone https://github.com/spacegraphcats/spacegraphcats/

cd spacegraphcats
pip install -r requirements.txt
```

And then I get the following error:
```
(catsenv) ubuntu@ip-172-31-17-27:~/bcalm/build/spacegraphcats$ pip install -r requirements.txt
Collecting screed<2,>=1.1 (from -r requirements.txt (line 1))
  Downloading screed-1.1.3.tar.gz (144 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.1/144.1 kB 5.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pytest>=5.1.2 (from -r requirements.txt (line 2))
  Downloading pytest-7.4.3-py3-none-any.whl.metadata (7.9 kB)
Collecting pytest-dependency (from -r requirements.txt (line 3))
  Downloading pytest-dependency-0.5.1.tar.gz (27 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy (from -r requirements.txt (line 4))
  Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Collecting pandas (from -r requirements.txt (line 5))
  Downloading pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting snakemake==7.30.1 (from -r requirements.txt (line 6))
  Downloading snakemake-7.30.1-py3-none-any.whl.metadata (2.8 kB)
Collecting click<9,>=8.1.2 (from -r requirements.txt (line 7))
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting sortedcontainers (from -r requirements.txt (line 8))
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting bbhash>=0.5 (from -r requirements.txt (line 9))
  Downloading bbhash-0.5.4.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/home/ubuntu/catsenv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/ubuntu/catsenv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/ubuntu/catsenv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-xhbvs9rj/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-xhbvs9rj/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-xhbvs9rj/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-xhbvs9rj/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

thanks for any help!

**Comment by taylorreiter** [comment]
Hi @jessicalumian! Can you try following the conda installation instructions? https://github.com/spacegraphcats/spacegraphcats/blob/latest/doc/00-installing-spacegraphcats.md#1-installing-dependencies-using-conda

**Comment by jessicalumian** [comment]
Those conda instructions worked for me on an ec2! I'll go that route instead of what I had above. thanks!
