### ISSUE TITLE
full 'hu' data set stuck (?) again

### ISSUE THREAD

**Issue by ctb** [spacegraphcats/spacegraphcats#72]
currently consuming 103 GB of RAM :)

```
added 10078109 fraternal edges
bucketed 15691969 of 15691969 nodes
removed 15691969 of 15691969 nodes
Computing step 3
added 78542082 transitive edges
added 8875408 fraternal edges
bucketed 14572440 of 14572440 nodes
removed 14572440 of 14572440 nodes
assigning to dominators
computing dominating edges
Adding edges between odd length optimal domination
Adding edges between even length optimal domination
Catlas level 0 complete
Computing low degree orientation (step 1)
bucketed 8607137 of 8607137 nodes
removed 8607137 of 8607137 nodes
assigning to dominators
computing dominating edges
Adding edges between odd length optimal domination
Adding edges between even length optimal domination
Catlas level 1 complete
Computing low degree orientation (step 1)
bucketed 3135254 of 3135254 nodes
removed 3135254 of 3135254 nodes
assigning to dominators
computing dominating edges
Adding edges between odd length optimal domination
Adding edges between even length optimal domination
Catlas level 2 complete
Computing low degree orientation (step 1)
bucketed 895356 of 895356 nodes
removed 895356 of 895356 nodes
assigning to dominators
computing dominating edges
Adding edges between odd length optimal domination
```

**Comment by ctb** [comment]
Note that this is being built with the version of spacegraphcats that includes checkpointing!!

**Comment by bdsullivan** [comment]
New implementation of adding edges between dominators by looping over v in the domgraph (instead of edges in either the original or domgraph) seems to have resolved this bottleneck. Need to re-run on podar and Hu to confirm success.

**Comment by ctb** [comment]
Update with latest master:

```
23709277 segments, containing 23709277 nodes
saving gxtfile hu_full/cdbg.gxt
reading graph
reading complete
building catlas
Computing low degree orientation (step 1)
bucketed 55038521 of 55038521 nodes
removed 55038521 of 55038521 nodes
Computing step 2
added 62922915 transitive edges
added 10078109 fraternal edges
bucketed 15691969 of 15691969 nodes
removed 15691969 of 15691969 nodes
Computing step 3
added 78542082 transitive edges
added 8875408 fraternal edges
bucketed 14572440 of 14572440 nodes
removed 14572440 of 14572440 nodes
assigning to dominators
computing dominating edges
Catlas level 0 complete
Writing to file hu_full/3_0.checkpoint
8607137
Computing low degree orientation (step 1)
bucketed 8607137 of 8607137 nodes
removed 8607137 of 8607137 nodes
assigning to dominators
computing dominating edges
Catlas level 1 complete
Writing to file hu_full/3_1.checkpoint
3134895
Computing low degree orientation (step 1)
bucketed 3134895 of 3134895 nodes
removed 3134895 of 3134895 nodes
assigning to dominators
computing dominating edges
Catlas level 2 complete
Writing to file hu_full/3_2.checkpoint
895355
Computing low degree orientation (step 1)
bucketed 895355 of 895355 nodes
removed 895355 of 895355 nodes
assigning to dominators
computing dominating edges
...
```

I can't tell if it's "stuck" yet, it's been running about 8 hours (but a lot of that was in building the gxt).

This is currently running in screen on the AWS host mentioned in slack, if anyone wants to take a look.

**Comment by ctb** [comment]
OK, I hit CTRL-C -- it failed to progress. I'm going to shut down the AWS machine as soon as I transfer data off.

I've put the cDBG/contigs here (1.2 GB)

https://osf.io/qcmwe/?show=revision

and the checkpoint files will be there shortly (4.5 GB).

together those two tar gz contain:

```
%  ls -l hu_full
total 17771736
-rw-rw-r-- 1 ubuntu ubuntu   916851773 May  7 10:13 3_0.checkpoint
-rw-rw-r-- 1 ubuntu ubuntu  1343148873 May  7 10:24 3_1.checkpoint
-rw-rw-r-- 1 ubuntu ubuntu 13184654643 May  7 11:04 3_2.checkpoint
-rw-rw-r-- 1 ubuntu ubuntu           0 May  7 08:54 catlas.csv
-rw-rw-r-- 1 ubuntu ubuntu  1133838588 May  7 08:53 cdbg.gxt
-rw-rw-r-- 1 ubuntu ubuntu   950116611 May  7 08:54 contigs.fa.gz
-rw-rw-r-- 1 ubuntu ubuntu   669608775 May  7 10:12 first_doms.txt
```

----

I hit CTRL-C and it yielded the following output:

```
Computing low degree orientation (step 1)
bucketed 895355 of 895355 nodes
removed 895355 of 895355 nodes
assigning to dominators
computing dominating edges


                   

^CTraceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/spacegraphcats/spacegraphcats/catlas.py", line 324, in <module>
    main(args)
  File "/home/ubuntu/spacegraphcats/spacegraphcats/catlas.py", line 306, in main
    level = level)
  File "/home/ubuntu/spacegraphcats/spacegraphcats/catlas.py", line 134, in build
    prev_nodes)
  File "/home/ubuntu/spacegraphcats/spacegraphcats/catlas.py", line 176, in _build_level
    domgraph, closest_dominators = domination_graph(graph, domset, radius)
  File "/home/ubuntu/spacegraphcats/spacegraphcats/rdomset.py", line 344, in domination_graph
    new_dom_neighbors |= closest_dominators[v]
KeyboardInterrupt
```

**Comment by ctb** [comment]
Hi all, I started hu up again, and it's still running. Looks like it's stuck in the same place as before -- but I don't have access to stdout on our cluster, so I can't be sure.

----
Command:

`python -m spacegraphcats.catlas hu_trim 3`

`ls` of the directory:

```
total 5755098
drwxr-sr-x 2 ctb ged-lab          9 May 28 15:57 .
drwxr-sr-x 4 ctb ged-lab         19 May 28 13:04 ..
-rw-r--r-- 1 ctb ged-lab  300498610 May 28 14:59 3_1.checkpoint
-rw-r--r-- 1 ctb ged-lab  430703972 May 28 15:20 3_2.checkpoint
-rw-r--r-- 1 ctb ged-lab 3219449225 May 28 17:07 3_3.checkpoint
-r--r--r-- 1 ctb ged-lab 1089508209 May 28 12:21 cdbg.gxt
-rw-r--r-- 1 ctb ged-lab        128 May 28 12:22 commands.log
-r--r--r-- 1 ctb ged-lab  922700591 May 28 12:21 contigs.fa.gz
-rw-r--r-- 1 ctb ged-lab  643028985 May 28 14:53 first_doms.txt
```

**Comment by ctb** [comment]
works!
