### ISSUE TITLE
Frontier search needs improvements

### ISSUE THREAD

**Issue by domoritz** [spacegraphcats/spacegraphcats#85]
- [x] Only resize the query mh if we need to (and memoize it)
- [x] Something is wrong with resizing. Try `time python -m search.frontier_search mircea-rm18.0.fa.sig podar 0.1` to see failure.

**Comment by domoritz** [comment]
I'm happy to fix this but I need some help from @ctb on the minhash code.

**Comment by ctb** [comment]
this is the error you're getting?
```
loaded 5320979 nodes from catlas podar/podar.catlas
loaded query sig mircea-rm18.0.fa
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/spacegraphcats/search/frontier_search.py", line 209, in <module>
    main()
  File "/home/ubuntu/spacegraphcats/search/frontier_search.py", line 184, in main   
    frontier, num_leaves, num_empty, frontier_mh = frontier_search(query_sig, top_node_id, dag, minhash_dir, args.overhead)
  File "/home/ubuntu/spacegraphcats/search/frontier_search.py", line 157, in frontier_search
    add_to_frontier(top_node_id)
  File "/home/ubuntu/spacegraphcats/search/frontier_search.py", line 103, in add_to_frontier
    containment = node_containment(minhash)
  File "/home/ubuntu/spacegraphcats/search/memoize.py", line 9, in memoized_func
    cache[key] = func(*args, **kwargs)
  File "/home/ubuntu/spacegraphcats/search/frontier_search.py", line 69, in node_containment
    return query_mh.containment(minhash)
  File "sourmash_lib/_minhash.pyx", line 370, in sourmash_lib._minhash.MinHash.containment (sourmash_lib/_minhash.cpp:7926)
  File "sourmash_lib/_minhash.pyx", line 240, in sourmash_lib._minhash.MinHash.count_common (sourmash_lib/_minhash.cpp:5665)
ValueError: different ksizes cannot be compared
```

my fault - that's because I computed the signatures with multiple k-mer sizes, and right now there's no way to ask the search functionality to load the "right" k-mer size from the query signature file (which can contain multiple k-mer sizes).  I recomputed all of the signatures with

```
sourmash compute -k 31 --scaled 5000 *.fa -f
```

and things now work. Apologies!

Leave this issue open and I'll figure out the right way to get ksize from the catlas and load the correct signature if it exists.

**Comment by ctb** [comment]
On the AWS machine I now get

```
% time python -m search.frontier_search mircea-rm18.0.fa.sig podar 0.1
loaded 5320979 nodes from catlas podar/podar.catlas
loaded query sig mircea-rm18.0.fa
Root containment: 0.627039627039627
Root similarity: 0.015652275107645757
Containment of frontier: 0.62004662004662
Similarity of frontier: 0.617169373549884
Size of frontier: 897666 of 5320979 (16.9%)
Number of leaves in the frontier: 3
Number of empty catlas nodes in the frontier: 897389
Size of the shadow: 1108319

real    1m14.235s
user    0m58.884s
sys     0m5.832s
```
